services:
  - type: web
    name: survive-the-rampage-multiplayer
    runtime: node
    buildCommand: npm ci
    startCommand: npm run start
    healthCheckPath: /health
    autoDeployTrigger: commit
